config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  namespace :admin do
    resources :users
  end
  resources :boards
  root to: 'boards#index'
  resources :comments, only:[:create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :delete_all 
    has_many :board_tag_relations, dependent: :delete_all
    has_many :tags, through: :board_tag_relations
    validates :title, presence: true
end

app/models/board_tag_relation.rb
class BoardTagRelation < ApplicationRecord
  belongs_to :board
  belongs_to :tag
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :board
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :board_tag_relations, dependent: :delete_all
    has_many :boards, through: :board_tag_relations
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    
    validates :name, presence: true
    validates :email,presence: true, uniqueness: true
    
    has_many :boards
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    
    if @user.save
      redirect_to admin_user_url(@user), notice: "ユーザー「#{@user.name}」を登録しました"
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    
    if @user.update(params[:id])
      redirect_to admin_user_url(@user), notice: "ユーザー「#{@user.name}」を更新しました。"
    else
      render :edit
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_url, notice: "ユーザー「#{@user.name}」を削除しました。"
  end
  
  def show
    @user = User.find(params[:id])
    @boards = @user.boards
  end

  def index
    @users = User.all
  end
  


  private
  
  def user_params
    params.require(:user).permit(:name, :email, :admin, :password, :password_confirmation)
  end
  
  def require_admin
    redirect_to root_url unless current_user.admin?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
    before_action :login_required
    
    
    private
    def current_user
        @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end
    
    def login_required
        redirect_to login_url unless current_user
    end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def index
    #@boards = params[:tag_id].present? ? Tag.find(params[:tag_id]).boards : Board.all
    @q = Board.ransack(params[:q])
    @tags = Tag.all
    @boards = @q.result(distinct: true).page(params[:page])
    #@boards = params[:tag_id].present? ? Tag.find(params[:tag_id]).boards : Board.all
    
  end

  def show
    @board = Board.find(params[:id])
    @comment = Comment.new(board_id: @board.id)
  end

  def new
    @board = Board.new
  end

  def edit
    @board = Board.find(params[:id])
  end
  
  def update
    board = Board.find(params[:id])
    board.update!(board_params)
    redirect_to boards_url, notice: "投稿「#{board.title}」を更新しました。"
  end
  
  def create
    @board = current_user.boards.new(board_params)
    if @board.save
      redirect_to @board, notice: "タスク「#{@board.title}」を登録しました。"
    else
      render :new
    end
  end
  
  def destroy
    @board = Board.find(params[:id])
    @board.destroy
    redirect_to boards_url, notice: "タスク「#{@board.title}」を削除しました。"
  end
  
  private
  
  def board_params
    params.require(:board).permit(:title, :context, tag_ids: [])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.new(comment_params)
    if comment.save
      flash.notice =  'コメントを投稿しました'
      redirect_to comment.board, notice: 'コメントを投稿しました'
    else
      redirect_to :back, flash: {
        comment: comment,
        error_messages: comment.errors.full_messages
      }
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.delete
    redirect_to comment.board,notice: 'コメントが削除されました' 
  end

  private

  def comment_params
    params.require(:comment).permit(:board_id, :name, :comment)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required
  
  
  def new
  end
  
  def create
    user = User.find_by(email: session_params[:email])
    
    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "ログインしました"
    else
      render :new
    end
  end
  
  def destroy
    reset_session
    redirect_to root_url,notice: 'ログアウトしました'
  end
  
  private
  
  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admin/users/_form.html.slim
-if user.errors.present? 
    - user.errors.full_messages.each do |message| 
        ul.error_explanation
            li
                = message
= form_with model: [:admin, user], local: true do |f|
  .form-group
    = f.label :name, '名前'
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :email, 'メールアドレス'
    = f.text_field :email, class: 'form-control'
  .form-check
    = f.label :admin, class: 'form-check-label' do
      = f.check_box :admin, class: 'form-check-input'
      | 管理者権限
  .form-group
    = f.label :password, 'パスワード'
    = f.password_field :password, class: 'form-control'
  .form-group
    = f.label :password_confirmation, 'パスワード(確認)'
    = f.password_field :password_confirmation, class: 'form-control'
  = f.submit '登録する', class: 'btn btn-primary'

app/views/admin/users/edit.html.slim
h1 ユーザー編集

.nav.justify-content-end
    = link_to "一覧",admin_users_path, class: "nav-link"

= render partial: "form", locals: {user: @user}

app/views/admin/users/index.html.slim
h1 ユーザー一覧

table.table.table-hover
    thead.thead-default
        tr
            th
                = User.human_attribute_name(:name)
            th
                = User.human_attribute_name(:email)
            th
                = User.human_attribute_name(:admin)
            th
                = User.human_attribute_name(:created_at)
            th
                = User.human_attribute_name(:updated_at)
    tbody
        - @users.each do |user| 
            tr
                td
                    = link_to user.name, [:admin, user] 
                td
                    = user.email 
                td
                    = user.admin? ? "あり" : "なし" 
                td
                    = user.created_at 
                td
                    = user.updated_at 
                td
                     = link_to "編集",edit_admin_user_path(user), class: "btn btn-primary mr-3" 
                     = link_to "削除",[:admin, user],method: :delete,data:{confirm: "ユーザー「#{user.name}」を削除します。よろしいですか？"},class: "btn btn-danger" 
= link_to "新規登録" ,new_admin_user_path, class: "btn btn-lg btn-primary" 

app/views/admin/users/new.html.slim
h1 ユーザー登録

.nav.justify-content-end
    = link_to "一覧",admin_users_path, class: "nav-link"

= render partial: "form", locals: {user: @user}

app/views/admin/users/show.html.slim
nav.justify-content-end
    = link_to "一覧",admin_users_path, class: "nav-link"
table.table.table-hover
    tbody.thead-default
        tr
            th
                = User.human_attribute_name(:id)
            td
                = @user.id
        tr
            th
                = User.human_attribute_name(:name)
            td
                = @user.name
        tr
            th
                = User.human_attribute_name(:email)
            td
                = @user.email 
        tr
            th
                = User.human_attribute_name(:admin)
            td
                = @user.admin? ? "あり" : " なし" 
        tr
            th
                = User.human_attribute_name(:created_at)
            td
                = @user.created_at 
        tr
            th
                = User.human_attribute_name(:updated_at)
            td
                = @user.updated_at
= link_to "編集",edit_admin_user_path, class: "btn btn-primary mr-3" 
= link_to "削除",[:admin,@user],method: :delete,class: "btn btn-danger" 

table.table.table-hover
  thead.thead-default
    tr
      th= Board.human_attribute_name(:title)
      th= Board.human_attribute_name(:created_at)
  tbody
    - @boards.each do |board|
      tr 
        td= link_to board.title, board
        td= link_to board.created_at, board
        td
          =link_to '編集',edit_board_path(board),class: 'btn btn-primary mr-3'
          =link_to '削除', board, method: :delete, data: {confirm: "投稿「#{board.title}」を削除してもよろしいですか？"},class: 'btn btn-danger'

app/views/boards/_board.html.slim
.card
  .card-header
    h4 = board.title 
    - board.tags.each do |tag| 
      span.badge.badge-primary = tag.name 
  .card-body
    p.card-text = simple_format(board.context) 
    p.text-right.font-weight-bold.mr-10 = board.title 

app/views/boards/edit.html.slim
h1 編集



= form_with model: @board, local: true do |f|
  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control', id: 'board_title'
  .form-group
    = f.label :context
    = f.text_area :context, rows: 5, class: 'form-control', id: 'board_context'
  .form-group
    span タグ
    = f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| 
      .form-check
        = tag.label class: 'form-check-label' do 
          = tag.check_box class: 'form-check-input' 
          = tag.text 
  = f.submit nil, class: 'btn btn-primary'

app/views/boards/index.html.slim
h1 投稿一覧

= link_to '新規登録', new_board_path, class: 'btn btn-primary mb-3'

= search_form_for @q,class: 'mb-5' do |f|
  .form-group.row
    = f.label :title,'タイトル',class: 'col-sm-2 col-form-label'
    .col-sm-10
      = f.search_field :title_cont,class: 'form_control'
  /.form-group.row
    = f.label :tag,'タグ',class: 'col-sm-2 col-form-label'
    .col-sm-10
      = f.collection_select :tag_id_cont,@tags,:id, :name, :include_blank => '指定なし',class: 'form_control'
  .form-group
    =f.submit class: 'btn btn-outline-primary'
    


= paginate @boards


.ml-auto.boards__linkBox
  = form_with url: boards_path, method: :get, class: 'boards__searchForm' do 
    = select_tag :tag_id,options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]),{prompt: 'タグで絞り込み',class: 'form-control boards__select',onchange: 'submit(this.form);'}
   


table.table.table-hover
  thead.thead-default
    tr
      th= Board.human_attribute_name(:title)
      th= Board.human_attribute_name(:created_at)
  tbody
    - @boards.each do |board|
      tr 
        td= link_to board.title, board
        td= link_to board.created_at, board
        td
          =link_to '編集',edit_board_path(board),class: 'btn btn-primary mr-3'
          =link_to '削除', board, method: :delete, data: {confirm: "投稿「#{board.title}」を削除してもよろしいですか？"},class: 'btn btn-danger'

app/views/boards/new.html.slim
- if @board.errors.present? 
  - @board.errors.full_messages.each do |message| 
    ul#error_explanation
      li= message
      
= form_with model: @board, local: true do |f|
  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control', id: 'board_title'
  .form-group
    = f.label :context
    = f.text_area :context, rows: 5, class: 'form-control', id: 'board_context'
  
  .form-group
    span タグ
    = f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| 
      .form-check
        = tag.label class: 'form-check-label' do 
          = tag.check_box class: 'form-check-input' 
          = tag.text 
  = f.submit nil, class: 'btn btn-primary'

app/views/boards/show.html.slim
h1 詳細表示


= render @board
= link_to '編集', edit_board_path, class: 'btn btn-primary mr-3'
= link_to '削除', @board, method: :delete, data: { confirm: "掲示板「#{@board.title}」を削除します。よろしいですか？" }, class: 'btn btn-danger'


.p-comment__list
  .p-comment__listTitle コメント
  = render @board.comments 

= render partial: 'comments/form', locals: { comment: @comment } 

app/views/comments/_comment.html.slim
.p-comment__item
  p = simple_format(comment.comment) 
  .p-comment__bottomLine
    = comment.name 
    = comment.created_at.to_s(:datetime_jp) 
    = link_to '削除', comment, method: :delete, data: {confirm: '削除してよろしいですか'},class: 'btn btn-danger'

app/views/comments/_form.html.slim
.p-comment__formBox
  p.p-comment__formTitle コメント記入
  = form_with model: comment do |f| 
    = f.hidden_field :board_id 
    .form-group
      = f.label :name, '名前' 
      = f.text_field :name, class: 'form-control' 
    .form-group
      = f.label :comment, 'コメント' 
      = f.text_area :comment, class: 'form-control', rows: 4 
    = f.submit '送信', class: 'btn btn-primary' 
 

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | PackerApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_pack_tag 'application'
  body
    .app-title.navbar.navbar-expand-md.navbar-light.bg-light
      .navbar-brand  packerapp
      ul.navbar-nav.ml-auto
        - if current_user
          li.nav-item = link_to "投稿一覧",boards_path,class: 'nav-link'
          - if current_user.admin?
            li.nav-item = link_to "ユーザー一覧",admin_users_path, class: 'nav-link'
          li.nav-item = link_to "ログアウト",logout_path, method: :delete,class: 'nav-link'
        - else
          li.nav-item = link_to "ログイン",login_path,class: 'nav-link'
    .container
      - if flash.notice.present?
        .alert.alert-success= flash.notice 
      = yield